name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests on'
        required: false
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  contents: read

env:
  CI: "true"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cypress-parallel:
    runs-on: ubuntu-latest
    container: cypress/included:14.5.3
    strategy:
      matrix:
        container: [1, 2]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create cypress.env.js from secret
        run: |
          echo "${{ secrets.ENV }}" > ./cypress.env.js

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache yarn dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Project Dependencies
        run: |
          yarn install --frozen-lockfile --no-fund
      
      - name: Run Cypress Tests in Parallel
        run: |
          ENV_INPUT="${{ github.event.inputs.environment || 'dev' }}"
          node cypressRunner.js --env "$ENV_INPUT" --record --parallel --key ${{ secrets.CYPRESS_RECORD_KEY }} --ci-build-id ${{ github.run_id }}-${{ github.run_attempt }}

      - name: Upload screenshots if they exist
        uses: actions/upload-artifact@v4
        if: always() && (hashFiles('cypress/screenshots/**') != '')
        with:
          name: cypress-screenshots-container-${{ matrix.container }}
          path: cypress/screenshots
          retention-days: 1

      - name: Upload videos if they exist
        uses: actions/upload-artifact@v4
        if: always() && (hashFiles('cypress/videos/**') != '')
        with:
          name: cypress-videos-container-${{ matrix.container }}
          path: cypress/videos
          retention-days: 1
      
      - name: Install Dependencies for Upload
        run: |
          apt-get update
          apt-get install -y curl jq
          
      - name: TestBeats Publish
        if: always()
        uses: test-results-reporter/publish@v1
        with:
          junit: 'cypress/reports/junit/*.xml'
          api-key: ${{ secrets.TESTBEATS_API_KEY }}