name: Cypress Tests
on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2] # Uses 2 parallel instances

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create cypress.env.js from secret
        run: |
          echo "${{ secrets.ENV }}" > ./cypress.env.js
      - name: Install project
        run: |
          npm install
      - name: Cypress run
        run: |
          node cypressRunner.js --env dev
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}